# Generated by Django 3.0.5 on 2020-07-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOfTasks',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='Tracking',
            new_name='Track',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name_task',
            new_name='name',
        ),
    ]
