# Generated by Django 3.0.5 on 2020-11-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200815_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.FloatField(help_text='Enter the rate value'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
